---
sidebar: sidebar 
permalink: concept-azure-netapp-files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: Mit Azure NetApp Files können Unternehmen ihre Performance-intensiven und latenzkritischen Core-Applikationen in Azure migrieren und ausführen, ohne für die Cloud einen Refactoring durchführen zu müssen. 
---
= Weitere Informationen zu Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit Azure NetApp Files können Unternehmen ihre Performance-intensiven und latenzkritischen Core-Applikationen in Azure migrieren und ausführen, ohne für die Cloud einen Refactoring durchführen zu müssen.



== Funktionen

* Da mehrere Protokolle unterstützt werden, kann das „Lift and Shift“ von Linux- und Windows-Applikationen nahtlos in Azure ausgeführt werden.
* Mehrere Performance-Tiers ermöglichen eine enge Ausrichtung an den Workload-Performance-Anforderungen.
* Hervorragende Zertifizierungen wie SAP HANA, DSGVO und HIPAA ermöglichen die Migration anspruchsvollster Workloads zu Azure.




== Zusätzliche Funktionen in BlueXP

* Migrieren Sie NFS- oder SMB-Daten direkt aus BlueXP zu Azure NetApp Files. Datenmigrationen werden durch die BlueXP Kopier- und Synchronisierungsfunktion unterstützt.
+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Weitere Informationen zum Kopieren und Synchronisieren von BlueXP"^]

* Mithilfe von künstlicher Intelligenz (KI) hilft Ihnen die BlueXP Klassifizierung dabei, den Datenkontext zu verstehen und sensible Daten in Ihren Azure NetApp Files-Konten zu identifizieren.
+
https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Weitere Informationen zur BlueXP Klassifizierung"^]





== Kosten

https://azure.microsoft.com/pricing/details/netapp/["Informieren Sie sich über die Preise für Azure NetApp Files"^]

Beachten Sie, dass Ihr Abonnement und Ihre Gebühren vom Azure NetApp Files-Service und nicht von BlueXP verwaltet werden.



== Unterstützte Regionen

https://cloud.netapp.com/cloud-volumes-global-regions["Unterstützte Azure Regionen anzeigen"^]



== Hilfe wird abgerufen

Bei Problemen mit dem technischen Support im Zusammenhang mit Azure NetApp Files können Sie im Azure-Portal eine Support-Anfrage an Microsoft protokollieren. Wählen Sie Ihr zugehöriges Microsoft-Abonnement aus, und wählen Sie den *Azure NetApp Files*-Dienstnamen unter *Speicherung* aus. Geben Sie die verbleibenden Informationen an, die für die Erstellung Ihrer Microsoft Support-Anfrage erforderlich sind.



== Weiterführende Links

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files auf der NetApp BlueXP Website"^]
* https://docs.microsoft.com/azure/azure-netapp-files/["Azure NetApp Files-Dokumentation"^]
* https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["Dokumentation der BlueXP Kopier- und Synchronisierungsfunktion"^]

