---
settings:
  name: Azure NetApp Files
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Azure NetApp Files Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Weitere Informationen zu Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Erste Schritte für den Workflow
      url: "/task-quick-start.html"
    - title: Richten Sie eine Microsoft Entra-Anwendung ein
      url: "/task-set-up-azure-ad.html"
    - title: Schaffen Sie eine Arbeitsumgebung
      url: "/task-create-working-env.html"
  - title: Verwenden Sie Azure NetApp Files
    entries:
    - title: Erstellung und Mounten von Volumes
      url: "/task-create-volumes.html"
    - title: Management vorhandener Volumes
      url: "/task-manage-volumes.html"
    - title: Entfernen Sie Azure NetApp Files
      url: "/task-remove-working-env.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
