---
settings:
  name: Azure NetApp Files
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: Azure NetApp Files Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Weitere Informationen zu Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Schnellstart
      url: "/task-quick-start.html"
    - title: Richten Sie eine Azure AD-Applikation ein
      url: "/task-set-up-azure-ad.html"
    - title: Schaffen Sie eine Arbeitsumgebung
      url: "/task-create-working-env.html"
  - title: Verwenden Sie Azure NetApp Files
    entries:
    - title: Erstellung und Mounten von Volumes
      url: "/task-create-volumes.html"
    - title: Management vorhandener Volumes
      url: "/task-manage-volumes.html"
    - title: Entfernen Sie Azure NetApp Files
      url: "/task-remove-working-env.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Weitere Informationen zu Azure NetApp Files
      url: concept-azure-netapp-files.html
    - title: Schnellstart
      url: task-quick-start.html
  - title: Verwenden Sie Azure NetApp Files
    links:
    - title: Volumes erstellen
      url: task-create-volumes.html
    - title: Volumes managen
      url: task-manage-volumes.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
